# Generated by Django 3.2.12 on 2022-04-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scode', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
