# Generated by Django 3.2.12 on 2022-04-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metar', '0002_auto_20220416_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=100)),
                ('last_observation', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
                ('wind', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Scode',
        ),
    ]
